# Generated by Django 6.1.1 on 2026-09-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_FAILED', 'Failed Login'), ('LOGIN_SUCCESS', 'Successful Login'), ('PRIVILEGE_CHANGE', 'Privilege Change'), ('SUSPICIOUS_REQUEST', 'Suspicious Request'), ('PORT_SCAN', 'Port Scan'), ('DATA_ACCESS', 'Data Access'), ('FILE_ACTIVITY', 'File Activity'), ('SYSTEM_EVENT', 'System Event'), ('OTHER', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
