# Generated by Django 6.1.1 on 2026-09-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='combined_risk_score',
            field=models.IntegerField(default=0, help_text='Unified risk: max of rule-based and ML signals.'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='ml_score',
            field=models.IntegerField(default=0, help_text='ML anomaly score, mirrored from AnomalyScore.normalized_score.'),
        ),
    ]
