# Generated by Django 6.1.1 on 2026-10-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('channel_type', models.CharField(choices=[('SLACK', 'Slack webhook'), ('EMAIL', 'Email')], default='SLACK', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Channel-specific configuration.')),
                ('enabled', models.BooleanField(default=True)),
                ('auto_notify', models.BooleanField(default=False, help_text='If True, SentinelX will automatically send HIGH/CRITICAL incident notifications to this channel as soon as an incident is created ? no playbook required.')),
                ('min_severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', help_text='Auto-notify only for incidents at or above this severity.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('payload_preview', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationchannel')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='incidents.incident')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='notificatio_sent_at_ab621c_idx')],
            },
        ),
    ]
