# Generated by Django 6.1.1 on 2026-09-26 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('IP', 'IP Address'), ('DOMAIN', 'Domain'), ('URL', 'URL'), ('HASH_MD5', 'MD5 Hash'), ('HASH_SHA256', 'SHA256 Hash'), ('EMAIL', 'Email')], max_length=20)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ioc_type', 'value'], name='threatintel_ioc_typ_aa2eeb_idx')],
                'constraints': [models.UniqueConstraint(fields=('ioc_type', 'value'), name='unique_ioc_type_value')],
            },
        ),
        migrations.CreateModel(
            name='IPReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('category', models.CharField(choices=[('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('MALICIOUS', 'Malicious'), ('SCANNER', 'Scanner'), ('TOR_EXIT', 'Tor Exit Node'), ('PROXY', 'Proxy / VPN'), ('BOTNET', 'Botnet C2'), ('SPAM', 'Spam Source'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('abuse_score', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('asn', models.CharField(blank=True, max_length=32, null=True)),
                ('asn_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='seed', max_length=32)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IP reputations',
                'ordering': ['-abuse_score', '-fetched_at'],
                'indexes': [models.Index(fields=['category'], name='threatintel_categor_9c5df4_idx'), models.Index(fields=['-abuse_score'], name='threatintel_abuse_s_17b9f0_idx')],
            },
        ),
    ]
