# Generated by Django 6.1.1 on 2026-09-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Raw model decision_function output.')),
                ('normalized_score', models.IntegerField(default=0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('model_version', models.CharField(default='v1', max_length=32)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_score', to='events.securityevent')),
            ],
            options={
                'ordering': ['-normalized_score', '-scored_at'],
                'indexes': [models.Index(fields=['-normalized_score'], name='ml_anomalys_normali_e25662_idx'), models.Index(fields=['is_anomaly'], name='ml_anomalys_is_anom_a4476b_idx')],
            },
        ),
    ]
