# Generated by Django 6.1.1 on 2026-09-25 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(choices=[('BRUTE_FORCE_LOGIN', 'Brute Force Login'), ('OFF_HOURS_ADMIN_LOGIN', 'Off-Hours Admin Login'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('PORT_SCAN_BURST', 'Port Scan Burst'), ('SUSPICIOUS_EXTERNAL_ACCESS', 'Suspicious External Access'), ('HIGH_RISK_CORRELATION', 'High-Risk Correlation')], max_length=64)),
                ('confidence', models.IntegerField(default=50, help_text='Confidence score 0–100 produced by the rule.')),
                ('reason', models.TextField(help_text='Human-readable explanation of why the rule fired.')),
                ('auto_escalated', models.BooleanField(default=False, help_text="True if this detection caused the event's risk to jump.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='events.securityevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rule_name'], name='detection_d_rule_na_14ca92_idx'), models.Index(fields=['-created_at'], name='detection_d_created_512b08_idx')],
            },
        ),
    ]
