# Generated by Django 6.1.1 on 2026-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(fields=('event', 'rule_name'), name='unique_detection_per_event_rule'),
        ),
    ]
