# Generated by Django 6.1.1 on 2026-10-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('trigger', models.JSONField(help_text='Trigger condition evaluated against each new incident.')),
                ('actions', models.JSONField(default=list, help_text='Ordered list of actions to execute on match.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('actions_run', models.JSONField(default=list, help_text='Log of each action executed and its result.')),
                ('error', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='incidents.incident')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='playbooks.playbook')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['-executed_at'], name='playbooks_p_execute_bac06e_idx'), models.Index(fields=['playbook', '-executed_at'], name='playbooks_p_playboo_1e0963_idx')],
            },
        ),
    ]
